### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by beraybentesen** [peterlee0127/tensorflow-tx2#1]
I receive this error : 
Processing ./tensorflow-1.3.0rc0-cp27-cp27mu-linux_aarch64.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 328, in run
    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 748, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 360, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 577, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 798, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 705, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python2.7/dist-packages/pip/utils/__init__.py", line 500, in unzip_file
    zipfp = open(filename, 'rb')
IOError: [Errno 2] No such file or directory: '/home/nvidia/tensorflow-1.3.0rc0-cp27-cp27mu-linux_aarch64.whl'

Also do I need to install any additional library etc. ?

**Comment by peterlee0127** [comment]
No need to install additional library. 
Please ensure you install the cuDNN 6.0 and CUDA 8.0 library. These file is in JetPack 3.1.
Other package will install by the pip automatically.

How is your pip version ?
$ pip --version
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)


My output is like this.
`➜  workspace sudo pip install tensorflow-1.3.0rc0-cp27-cp27mu-linux_aarch64.whl
Processing ./tensorflow-1.3.0rc0-cp27-cp27mu-linux_aarch64.whl
Collecting protobuf>=3.2.0 (from tensorflow==1.3.0rc0)
  Downloading protobuf-3.3.0.tar.gz (271kB)
    100% |████████████████████████████████| 276kB 25kB/s
Requirement already satisfied: six>=1.10.0 in /usr/lib/python2.7/dist-packages (from tensorflow==1.3.0rc0)
Collecting tensorflow-tensorboard (from tensorflow==1.3.0rc0)
  Downloading tensorflow_tensorboard-0.1.2-py2-none-any.whl (1.3MB)
...........`
